export default {
  SET_PREVIOUS_ROUTE_STATE: 'SET_PREVIOUS_ROUTE_STATE',
  SET_USER_STATE: 'SET_USER_STATE',
  SET_SEMESTER_STATE: 'SET_SEMESTER_STATE',
  SET_YEAR_STATE: 'SET_YEAR_STATE',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  SET_PM_FLAG: 'SET_PM_FLAG',
  SET_ID_TEAM: 'SET_ID_TEAM',
  SET_USER_ROLE: 'SET_USER_ROLE',
  SET_ID_MANAGER: 'SET_ID_MANAGER',
  SET_PRODUCTIVE: 'SET_PRODUCTIVE',
  SET_NEUTRAL: 'SET_NEUTRAL',
  SET_UNPRODUCTIVE: 'SET_UNPRODUCTIVE'
}
